import { Inter, Lato } from "next/font/google";
import "./globals.css";
import Header from "./components/header";
import NavBar from "./components/NavBar";

// const inter = Inter({ subsets: ["latin"] });
const lato = Lato({ subsets: ["latin"], weight: ["400", "700"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      {/* <body className={inter.className}> */}
      <body className={lato.className}>
        <Header />
        <div className="app-container">
          <NavBar />
          {children}
        </div>
      </body>
    </html>
  );
}
